server:
  port: 8083

spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:    console:      enabled: true
  security:
    oauth2:
      resourceserver:
        jwt:
          # jwk-set-uri: https://oauth2.googleapis.com/token
          issuer-uri: https://accounts.google.com  mvc:    log-request-details: true    publish-request-handled-events: true
logging:  level:    test: debug
    root: info
    '[org.springframework.boot.autoconfigure]': info
    '[org.springframework.web]': debug
    '[org.springframework.web.filter]': debug
    '[org.springframework.web.HttpLogging]': debug
    '[org.springframework.security]': debug
    '[org.springframework.security.oauth2]': debug